//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public Category()
    {
        this.Products = new HashSet<Product>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Product> Products { get; set; }
}

public partial class Comment
{
    public int CommentID { get; set; }
    public string CommentText { get; set; }
    public int CustomerID { get; set; }
    public int ProductID { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Comments = new HashSet<Comment>();
        this.Orders = new HashSet<Order>();
    }

    public int CustomerID { get; set; }
    public string UserName { get; set; }
    public string PWD { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Marital_Status { get; set; }
    public string Gender { get; set; }
    public Nullable<double> Income { get; set; }
    public Nullable<double> Children { get; set; }
    public string Education { get; set; }
    public string Occupation { get; set; }
    public string Home_Owner { get; set; }
    public Nullable<double> Cars { get; set; }
    public string Commute_Distance { get; set; }
    public string Region { get; set; }
    public Nullable<double> Age { get; set; }
    public string Buy { get; set; }
    public bool Is_Admin { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.OrdersDetails = new HashSet<OrdersDetail>();
    }

    public string OrderID { get; set; }
    public Nullable<int> CustomerID { get; set; }
    public Nullable<System.DateTime> ordDate { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
}

public partial class OrdersDetail
{
    public int OrdsID { get; set; }
    public string OrderID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<double> ProductPrice { get; set; }

    public virtual Order Order { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.Comments = new HashSet<Comment>();
        this.OrdersDetails = new HashSet<OrdersDetail>();
        this.Rates = new HashSet<Rate>();
    }

    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public Nullable<double> ProductPrice { get; set; }
    public string Manufacturer { get; set; }
    public string Features { get; set; }
    public string Description { get; set; }
    public int CategoryID { get; set; }

    public virtual Category Category { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
    public virtual ICollection<Rate> Rates { get; set; }
}

public partial class Rate
{
    public int RateID { get; set; }
    public int RateValue { get; set; }
    public int ProductID { get; set; }

    public virtual Product Product { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Get_monthly_Report_Result
{
    public Nullable<System.DateTime> ordDate { get; set; }
    public Nullable<double> total { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
